### ISSUE TITLE
List buttons broken in Kitchen Sink demo

### ISSUE THREAD

**Issue by abarth** [zanderso/chicago#1] opened 2021-04-28 00:49 UTC
In the "lists" section, I can't change the Clock to the Anchor under the List Buttons header.

1. Clock on the down arrow.
2. See the menu appear.
3. Click on the Anchor.
4. Nothing happens.

Expected behavior: The menu closes and I see the Anchor displayed in the button.

Actual behavior: The menu remains open.  If I click away, the Clock is still selected.

The same thing happens with the Basic and Color example List Buttons.

**Comment by abarth** [comment] 2021-04-28 00:49
I'm using Chrome on a Mac.

**Comment by tvolkert** [comment] 2021-05-21 04:25
Bisected to a64f31ce586d37824a5ace760ccf2b73dedec491

**Comment by tvolkert** [comment] 2021-05-21 05:08
The issue is that a64f31c switched RenderListView to use gesture recognizers rather than raw pointer event handling, and in so doing, it caused RenderListView's tap gesture recognizer[1] to win the arena -- and conversely, _PopupListState's tap gesture recognizer[2] to lose the arena.  The latter is what closes the popup and sets the selected index of the button.

[1] https://github.com/tvolkert/chicago/blob/d68b53c87e933a1a1a3f5a233b14fc07c058acf5/lib/src/list_view.dart#L508-L511

[2] https://github.com/tvolkert/chicago/blob/d68b53c87e933a1a1a3f5a233b14fc07c058acf5/lib/src/list_button.dart#L805-L806

**Comment by tvolkert** [comment] 2021-05-21 05:27
Fixed by 557dea2

**Closed as completed by tvolkert** 2021-05-21 05:27 UTC

**Comment by abarth** [comment] 2021-05-21 07:43
Thanks!
